resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/mithunmo/con-ci.git
#- name: resource-app
#  type: git
#  source:
#    uri: https://github.com/cloudfoundry-community/simple-go-web-app.git

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resource-tutorial
    trigger: true
  - task: test1
    file: resource-tutorial/task.yml
  - task: test2
    file: resource-tutorial/task2.yml
    
